<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\common.props" />

  <PropertyGroup>
    <RootNamespace>FhirAugury.Processing.Client</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\FhirAugury.Common\FhirAugury.Common.csproj" />
    <ProjectReference Include="..\FhirAugury.Processing.Contracts\FhirAugury.Processing.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="FhirAugury.Processing.Client.Tests" />
  </ItemGroup>
</Project>
