<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>FhirAugury.Testing.Sqlite</RootNamespace>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Update="SourceGear.sqlite3" Version="3.53.3" />
    <PackageReference Update="SQLitePCLRaw.provider.e_sqlite3" Version="3.0.3" />
  </ItemGroup>

</Project>
