<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>14.0</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <IsPackable>false</IsPackable>
    <RootNamespace>FhirAugury.Processor.GitHub.Fhir.BallotNotes.Tests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.4" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
    <Using Include="FhirAugury.Testing.Sqlite" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\FhirAugury.Processor.GitHub.Fhir.BallotNotes.Persistence\FhirAugury.Processor.GitHub.Fhir.BallotNotes.Persistence.csproj" />
    <ProjectReference Include="..\..\src\FhirAugury.Processor.GitHub.Fhir.BallotNotes.Hydration\FhirAugury.Processor.GitHub.Fhir.BallotNotes.Hydration.csproj" />
    <ProjectReference Include="..\FhirAugury.Testing.Sqlite\FhirAugury.Testing.Sqlite.csproj" />
  </ItemGroup>
</Project>
