<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\..\src\common.props" />
  <Import Project="..\..\src\sqlite.props" />

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>FhirAugury.Tools.TicketSite</RootNamespace>
    <AssemblyName>ticket-site</AssemblyName>
    <IsPackable>false</IsPackable>
    <InvariantGlobalization>true</InvariantGlobalization>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\FhirAugury.Common\FhirAugury.Common.csproj" />
    <ProjectReference Include="..\..\src\FhirAugury.Processing.Client\FhirAugury.Processing.Client.csproj" />
    <ProjectReference Include="..\..\src\FhirAugury.Processing.Contracts\FhirAugury.Processing.Contracts.csproj" />
    <ProjectReference Include="..\..\src\FhirAugury.Publishing.Tickets\FhirAugury.Publishing.Tickets.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="FhirAugury.Tools.TicketSite.Tests" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Update="SourceGear.sqlite3" Version="3.53.3" />
    <PackageReference Update="SQLitePCLRaw.provider.e_sqlite3" Version="3.0.3" />
  </ItemGroup>
</Project>
