<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\common.props" />

  <PropertyGroup>
    <RootNamespace>FhirAugury.Processor.Jira.Fhir.Planner.Hydration</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="10.0.*" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.*" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="10.0.*" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FhirAugury.Processor.Jira.Fhir.Hydration.Common\FhirAugury.Processor.Jira.Fhir.Hydration.Common.csproj" />
    <ProjectReference Include="..\FhirAugury.Processor.Jira.Fhir.Planner.Persistence\FhirAugury.Processor.Jira.Fhir.Planner.Persistence.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="FhirAugury.Processor.Jira.Fhir.Planner" />
    <InternalsVisibleTo Include="FhirAugury.Processor.Jira.Fhir.Planner.Tests" />
  </ItemGroup>
</Project>
