using FhirAugury.Service;

namespace FhirAugury.Integration.Tests;

public class IngestionQueueTests
{
    [Fact]
    public async Task Enqueue_Dequeue_RoundTrip()
    {
        var queue = new IngestionQueue(capacity: 10);
        var request = new IngestionRequest
        {
            SourceName = "jira",
            Type = Models.IngestionType.Incremental,
        };

        await queue.EnqueueAsync(request);
        Assert.Equal(1, queue.Count);

        Assert.True(queue.TryDequeue(out var dequeued));
        Assert.NotNull(dequeued);
        Assert.Equal("jira", dequeued.SourceName);
        Assert.Equal(0, queue.Count);
    }

    [Fact]
    public async Task Enqueue_Multiple_MaintainsOrder()
    {
        var queue = new IngestionQueue(capacity: 10);

        var r1 = new IngestionRequest { SourceName = "jira", Type = Models.IngestionType.Full };
        var r2 = new IngestionRequest { SourceName = "zulip", Type = Models.IngestionType.Incremental };
        var r3 = new IngestionRequest { SourceName = "jira", Type = Models.IngestionType.OnDemand, Identifier = "FHIR-123" };

        await queue.EnqueueAsync(r1);
        await queue.EnqueueAsync(r2);
        await queue.EnqueueAsync(r3);

        Assert.Equal(3, queue.Count);

        Assert.True(queue.TryDequeue(out var d1));
        Assert.Equal("jira", d1!.SourceName);
        Assert.Equal(Models.IngestionType.Full, d1.Type);

        Assert.True(queue.TryDequeue(out var d2));
        Assert.Equal("zulip", d2!.SourceName);

        Assert.True(queue.TryDequeue(out var d3));
        Assert.Equal("FHIR-123", d3!.Identifier);
    }

    [Fact]
    public async Task Bounded_Capacity_BlocksWriter()
    {
        var queue = new IngestionQueue(capacity: 2);

        await queue.EnqueueAsync(new IngestionRequest { SourceName = "a", Type = Models.IngestionType.Full });
        await queue.EnqueueAsync(new IngestionRequest { SourceName = "b", Type = Models.IngestionType.Full });

        // Queue is now full — enqueue should block/timeout
        using var cts = new CancellationTokenSource(TimeSpan.FromMilliseconds(200));
        await Assert.ThrowsAsync<OperationCanceledException>(async () =>
        {
            await queue.EnqueueAsync(
                new IngestionRequest { SourceName = "c", Type = Models.IngestionType.Full },
                cts.Token);
        });
    }

    [Fact]
    public async Task DequeueAllAsync_ReceivesItems()
    {
        var queue = new IngestionQueue(capacity: 10);
        var received = new List<string>();

        using var cts = new CancellationTokenSource(TimeSpan.FromSeconds(2));

        // Producer
        _ = Task.Run(async () =>
        {
            await queue.EnqueueAsync(new IngestionRequest { SourceName = "src1", Type = Models.IngestionType.Full });
            await queue.EnqueueAsync(new IngestionRequest { SourceName = "src2", Type = Models.IngestionType.Full });
            await Task.Delay(100);
            cts.Cancel();
        });

        // Consumer
        try
        {
            await foreach (var item in queue.DequeueAllAsync(cts.Token))
            {
                received.Add(item.SourceName);
            }
        }
        catch (OperationCanceledException)
        {
            // Expected
        }

        Assert.Contains("src1", received);
        Assert.Contains("src2", received);
    }

    [Fact]
    public async Task ConcurrentAccess_ThreadSafe()
    {
        var queue = new IngestionQueue(capacity: 50);
        var enqueueCount = 20;
        var received = new System.Collections.Concurrent.ConcurrentBag<string>();

        using var cts = new CancellationTokenSource(TimeSpan.FromSeconds(5));

        // Multiple producers
        var producers = Enumerable.Range(0, 4).Select(i => Task.Run(async () =>
        {
            for (var j = 0; j < enqueueCount / 4; j++)
            {
                await queue.EnqueueAsync(
                    new IngestionRequest { SourceName = $"src-{i}-{j}", Type = Models.IngestionType.Full },
                    cts.Token);
            }
        }));

        // Consumer
        var consumer = Task.Run(async () =>
        {
            try
            {
                await foreach (var item in queue.DequeueAllAsync(cts.Token))
                {
                    received.Add(item.SourceName);
                    if (received.Count >= enqueueCount) cts.Cancel();
                }
            }
            catch (OperationCanceledException) { }
        });

        await Task.WhenAll(producers);
        await consumer;

        Assert.Equal(enqueueCount, received.Count);
    }

    [Fact]
    public void RequestId_AutoGenerated()
    {
        var r1 = new IngestionRequest { SourceName = "test", Type = Models.IngestionType.Full };
        var r2 = new IngestionRequest { SourceName = "test", Type = Models.IngestionType.Full };

        Assert.NotEmpty(r1.RequestId);
        Assert.NotEmpty(r2.RequestId);
        Assert.NotEqual(r1.RequestId, r2.RequestId);
    }
}
