<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>14.0</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <IsPackable>false</IsPackable>
    <RootNamespace>FhirAugury.Tools.FhirXverElementDiff.Tests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="10.0.1">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.7.0" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.5">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
    <Using Include="FhirAugury.Testing.Sqlite" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\tools\fhir-xver-element-diff\fhir-xver-element-diff.csproj" />
    <ProjectReference Include="..\FhirAugury.Testing.Sqlite\FhirAugury.Testing.Sqlite.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Update="SourceGear.sqlite3" Version="3.53.3" />
    <PackageReference Update="SQLitePCLRaw.provider.e_sqlite3" Version="3.0.3" />
  </ItemGroup>
</Project>
